### ISSUE TITLE
Error loading InfraView after running update_infrapy.sh

### ISSUE THREAD

**Issue by aileen-fisher** [LANL-Seismoacoustics/infrapy#20]
(infrapy_env) bash-4.2$ infraview
cpu count = 4
Traceback (most recent call last):
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/bin/infraview", line 8, in <module>
    sys.exit(main())
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/__main__.py", line 29, in main
    aw = IPApplicationWindow(qApp, progname, progversion)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPApplicationWindow.py", line 77, in __init__
    self.buildUI()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPApplicationWindow.py", line 94, in buildUI
    self.locationWidget = IPLocationWidget.IPLocationWidget(self, self.mp_pool)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPLocationWidget.py", line 55, in __init__
    self.buildUI()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPLocationWidget.py", line 64, in buildUI
    self.mapWidget = IPMapWidget.IPMapWidget(self)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPMapWidget.py", line 57, in __init__
    self.buildUI()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPMapWidget.py", line 99, in buildUI
    self.draw_map()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPMapWidget.py", line 192, in draw_map
    self.update_feature_visibilities()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/InfraView/widgets/IPMapWidget.py", line 230, in update_feature_visibilities
    self.fig.canvas.draw()  # update matlabplot
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/backends/backend_agg.py", line 400, in draw
    self.figure.draw(self.renderer)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/figure.py", line 3140, in draw
    mimage._draw_list_compositing_images(
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/image.py", line 131, in _draw_list_compositing_images
    a.draw(renderer)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 502, in draw
    self._draw_preprocess(renderer)
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 468, in _draw_preprocess
    self.autoscale_view()
  File "/data/studies/PyGS/miniconda3/envs/infrapy_env/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 901, in autoscale_view
    if scalex and self._autoscaleXon:
AttributeError: 'GeoAxes' object has no attribute '_autoscaleXon'

**Comment by jwebster-LANL** [comment]
Hmm, this hasn't happened on any of my systems (yet?)

Let me look into this.  Can you check to see what version of cartopy is installed on your system?  

`>> conda list | grep cartopy`

**Comment by jwebster-LANL** [comment]
Oh, and what version of matplotlib?

I suspect it's related to [this](https://github.com/SciTools/cartopy/issues/2086)

**Comment by aileen-fisher** [comment]
Hi Jeremy :) 

(infrapy_env) bash-4.2$ conda list | grep cartopy
cartopy                   0.19.0.post1     py39h3b23250_1    conda-forge
(infrapy_env) bash-4.2$ conda list | grep matplotlib
matplotlib-base           3.7.1            py39h417a72b_1  
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge

**Comment by aileen-fisher** [comment]
I haven't updated that cartopy shapefiles download, but this was on the low side so I don't think it would have become an error on startup.

**Comment by jwebster-LANL** [comment]
For some reason conda wasnt automatically updating cartopy from 0.19 to 0.21.  I updated the yml file to force its version to be >= 21 so that should help.  Also, while I was at it I switched it to download pisces from pypi instead of the git repository.  

Do another update_infrapy.sh and let me know if it works again.

**Comment by aileen-fisher** [comment]
So I ran update again and it's still keeping cartopy at 0.19:

`(infrapy_env) bash-4.2$ pip list | grep Cartopy
Cartopy                       0.19.0.post1`

Not sure why.  I'll rerun and try doing some forcing.

**Comment by aileen-fisher** [comment]
Opens now.  Thank you!

**Comment by jwebster-LANL** [comment]
Lol, I didn't do anything?  I dunno.  There have been some issues with cartopy and some other things lately.  So annoying.

From: aileen-fisher ***@***.***>
Sent: Thursday, August 24, 2023 1:32 PM
To: LANL-Seismoacoustics/infrapy ***@***.***>
Cc: Webster, Jeremy David ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [LANL-Seismoacoustics/infrapy] Error loading InfraView after running update_infrapy.sh (Issue #20)


Opens now. Thank you!
