### ISSUE TITLE
can not open infraview

### ISSUE THREAD

**Issue by chdyxh** [LANL-Seismoacoustics/infrapy#22]
**Error details:**
(infrapy_env) yxh@yxh-virtual-machine:/usr/local/infrapy$ infraview
RuntimeError: The new DType API is currently in an exploratory phase and should NOT be used for production code.  Expect modifications and crashes!  To experiment with the new API you must set `NUMPY_EXPERIMENTAL_DTYPE_API=1` as an environment variable.
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/infrapy_env/bin/infraview", line 33, in <module>
    sys.exit(load_entry_point('infrapy', 'gui_scripts', 'infraview')())
  File "/usr/local/anaconda3/envs/infrapy_env/bin/infraview", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/anaconda3/envs/infrapy_env/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/usr/local/anaconda3/envs/infrapy_env/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/infrapy/InfraView/__main__.py", line 10, in <module>
    from InfraView.widgets.IPApplicationWindow import *
  File "/usr/local/infrapy/InfraView/widgets/IPApplicationWindow.py", line 29, in <module>
    from InfraView.widgets import IPLocationWidget
  File "/usr/local/infrapy/InfraView/widgets/IPLocationWidget.py", line 24, in <module>
    from infrapy.location import bisl
  File "/usr/local/infrapy/infrapy/location/bisl.py", line 26, in <module>
    from ..utils import latlon as ll
  File "/usr/local/infrapy/infrapy/utils/latlon.py", line 36, in <module>
    from numpy.core.umath_tests import inner1d
  File "/usr/local/anaconda3/envs/infrapy_env/lib/python3.9/site-packages/numpy/core/umath_tests.py", line 13, in <module>
    from ._umath_tests import *
RuntimeError: cannot load _umath_tests module.

I reinstalled anaconda and infrapy and opened infraview again, but it still failed.

**Systerm information:** ubuntu 22.04  runs in the virtual mechine

**Comment by chdyxh** [comment]
numpy version: 1.25.2

Similar issue: https://github.com/numba/numba/issues/8698#issuecomment-1584888063

**Comment by dng12345** [comment]
We have observed the same issue with fresh installs on both Windows and Mac.

Agree with @chdyxh that it is likely a NumPy compatibility issue. Changing conda environment .yml file so that NumPy 1.24.3 is version within infrapy_env ensures infraview works.

**Comment by chdyxh** [comment]
> We have observed the same issue with fresh installs on both Windows and Mac.
> 
> Agree with @chdyxh that it is likely a NumPy compatibility issue. Changing conda environment .yml file so that NumPy 1.24.3 is version within infrapy_env ensures infraview works.

Yes! I set the version of Numpy 1.24.3 in infrapy_env.yml file as you say, and infraview works. Thank you.

**Comment by jwebster-LANL** [comment]
Hey, apologies this took so long, github locked me out.  I pinned numpy to 1.24.3 in the yml setup file.  Could someone give it a test and see if things are good?  Then I will close this.

**Comment by chdyxh** [comment]
> Hey, apologies this took so long, github locked me out. I pinned numpy to 1.24.3 in the yml setup file. Could someone give it a test and see if things are good? Then I will close this.

 

> Hey, apologies this took so long, github locked me out. I pinned numpy to 1.24.3 in the yml setup file. Could someone give it a test and see if things are good? Then I will close this.

I set the version of Numpy to 1.24.3 in infrapy_env.yml file and infraview works well.

**Comment by jwebster-LANL** [comment]
Marking this closed.  If you have this issue, run the update_infrapy script in the root directory to hopefully fix the numpy version.  Anyone who continues to have the issue, let me know and I'll take another look.
